services:
  e470-auditlog-web-api:
    image: ${DOCKER_REGISTRY-}e470-auditlog-webapi
    container_name: e470-auditlog-web-api
    build:
      context: .
      dockerfile: src/E470.AuditLog.Web.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__audit-log-db=Server=mssql;Database=E470AuditLogDb;User Id=sa;Password=Pass@word1;TrustServerCertificate=True;
    depends_on:
      - mssql
  mssql:
    extends:
      file: compose.mssql.yml
      service: mssql
