services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__audit-log-db=Server=mssql;Database=WebApiDb;User Id=sa;Password=Pass@word1;TrustServerCertificate=True;
    depends_on:
      - mssql
  mssql:
    extends:
      file: compose.mssql.yml
      service: mssql
  